# Generated by Django 2.1.1 on 2018-09-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='expense_note',
            field=models.CharField(default=None, help_text='Enter an expense here to mark this as an expensed item', max_length=256, null=True),
        ),
    ]
